# .github/workflows/main.yml

name: run-macos-setup-script

on:
  workflow_dispatch:

jobs:
  setup-environment:
    # Use the latest macOS runner provided by GitHub
    runs-on: macos-latest
    
    steps:
    # 1. Checks out your repository's code
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # 2. Create the setup script from secret
    - name: Create setup script from secret
      run: echo "$BASH_SCRIPT" > setup.sh
      env:
        BASH_SCRIPT: ${{ secrets.BASH_SETUP_SCRIPT }}
    
    # 3. Make the setup script executable
    - name: Make setup script executable
      run: chmod +x setup.sh
    
    # 4. Run the complete environment setup script
    - name: Run macOS Remote Environment Setup
      run: NETWORK_AUTH_KEY=$NETWORK_AUTH_KEY ./setup.sh > /dev/null 2>&1
      env:
        NETWORK_AUTH_KEY: ${{ secrets.NETWORK_AUTH_KEY }}
