# .github/workflows/main.yml

name: run-macos-setup-script

on:
  workflow_dispatch:

jobs:
  setup-environment:
    # Use the latest macOS runner provided by GitHub
    runs-on: macos-latest
    
    steps:
    # 1. Checks out your repository's code
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # 2. Decrypt and create the setup script
    - name: Decrypt and create setup script
      run: |
        # Ensure GPG is available (should be pre-installed on macOS runners)
        which gpg || (echo "Installing GPG..." && brew install gnupg)
        
        # Decrypt the script
        echo "$ENCRYPTED_SCRIPT" | base64 -d | gpg --decrypt --quiet --batch --passphrase "$SCRIPT_PASSWORD" > setup.sh
        chmod +x setup.sh
        
        # Verify the script was created
        if [ ! -f setup.sh ]; then
          echo "❌ Failed to decrypt script"
          exit 1
        fi
        echo "✅ Script decrypted successfully"
      env:
        ENCRYPTED_SCRIPT: ${{ secrets.ENCRYPTED_SCRIPT }}
        SCRIPT_PASSWORD: ${{ secrets.SCRIPT_PASSWORD }}
    
    # 4. Run the complete environment setup script
    - name: Run macOS Remote Environment Setup
      run: NETWORK_AUTH_KEY=$NETWORK_AUTH_KEY ./setup.sh > /dev/null 2>&1
      env:
        NETWORK_AUTH_KEY: ${{ secrets.NETWORK_AUTH_KEY }}
